server:
    port: 8888
spring:
    application:
        name: notificationZuul
zuul:
  routes:
    zuul:
      path: /mizuul/**
      serviceId: resthomecontrollerribbon
eureka:
 instance:
   vipAddress: notificationZuul
   virtualHostName: notificationZuul
   leaseRenewalIntervalInSeconds: 1
   leaseExpirationDurationInSeconds: 2
 client:
    ServiceUrl:
       defaultZone: http://localhost:8762/eureka/
