server:
    port: 8093
spring:
    application:
        name: configuracionusuarios
eureka:
 instance:
   vipAddress: configuracionusuarios
   virtualHostName: configuracionusuarios
   leaseRenewalIntervalInSeconds: 1
   leaseExpirationDurationInSeconds: 2