server:
    port: 8093
spring:
    application:
        name: configuracionusuarios
    data:
        mongodb.uri: mongodb://w963363D.ad.bbva.com:27017/dbTaller
eureka:
 instance:
   vipAddress: configuracionusuarios
   virtualHostName: configuracionusuarios
   leaseRenewalIntervalInSeconds: 1
   leaseExpirationDurationInSeconds: 2